### ISSUE TITLE
Why the limit of the result of followers is 200

### ISSUE THREAD

**Issue by spritrl** [instagram4j/instagram4j#169]
Hi !
i don't understand Why the limit of the result of followers is 200.
It's an API limit ?

I DO :
`InstagramSearchUsernameResult userResult = instagram
					.sendRequest(new InstagramSearchUsernameRequest("github"));
			InstagramGetUserFollowersResult githubFollowers = instagram
					.sendRequest(new InstagramGetUserFollowersRequest(userResult.getUser().getPk()));
			System.out.println("Followers size : "+githubFollowers.getUsers().size());`

RESULT : "Followers size : 200" (66,2k on instagram)

Can you help me?
Thanks.

**Comment by spritrl** [comment]
Two months ago when we were doing:
`InstagramGetUserFollowersResult followersResult = instagram
.sendRequest(new InstagramGetUserFollowersRequest(instagram.getUserId()));
System.out.println("Follower size: " + followersResult.getUsers().size());`
It worked ! But why today it doesn't work anymore?

**Comment by juandelia** [comment]
For Some reason I dont know, sometimes the results are much much higher, like 7k, but the next_max_id comes null, so you wouldnt be able to get the rest.

If the account you are using is fully enabled, the expected behavior I get is the one described by @jvogit where the results come in batchs of 200 users.

Best regards!
