### ISSUE TITLE
What does friendships/autocomplete_user_list/ request do?

### ISSUE THREAD

**Issue by onatbuyukakkus** [instagram4j/instagram4j#171]
What does this request do exactly?

**Comment by brunocvcunha** [comment]
Not a lot of practical usage, but it is something related to pre-cache the content when you start typing something in the search bar.
The reason why we keep it is to mimic the calls that the real app does when you login. Otherwise, they could just identify bot traffic by looking at the logins that are not running what the app is supposed to run by default.
