### ISSUE TITLE
get DMs media url

### ISSUE THREAD

**Issue by AhmedNader65** [instagram4j/instagram4j#369]
hi,
how can i get the media url from InstagramInboxThreadResult ? 

that's how the result looks like

> InstagramInboxThreadItem(super=org.brunocvcunha.instagram4j.requests.payload.InstagramInboxThreadItem@da2b0e2, item_id=28812432935757590471924750351335424, user_id=1255687260, timestamp=1561925119177064, item_type=media, like=null, text=null, reel_share=null)

**Comment by jemand771** [comment]
Hey, I had this working at some point. I closed the PR again because we split some tasks, but basically you can simply add one line to your `InstagramInboxThreadItem` which will add the property and basically do what you want.

https://github.com/jemand771/instagram4j/blob/8667f96a88e27f7b154ccca37d8cdda1dfa0c0fa/src/main/java/org/brunocvcunha/instagram4j/requests/payload/InstagramInboxThreadItem.java#L40

I'll look through the PRs and see if this change is already queued somewhere, if not I'll open a new one.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
