### ISSUE TITLE
Error message on InstagramGetUserFollowersRequest

### ISSUE THREAD

**Issue by marievixezonaki** [instagram4j/instagram4j#442]
Hello,

I have been trying to get a user's followers, and I was succeeding all the times until yesterday, when all of a sudden I got this message:

`InstagramGetUserFollowersResult(super=StatusResult(status=fail, message=Please wait a few minutes before you try again., spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), big_list=false, next_max_id=null, page_size=0, users=null)
`

Is there any clue what is happening?

**Comment by WebDirigent** [comment]
Followers working fine for me - got the same problem with the InstagramGetMediaLikersResult: Status "fail" and StatusMessage "Please wait a few minutes before you try again."

Could you solve your problem?

**Comment by f0lik** [comment]
Hey! The issue is that Instagram itself doesn't want their users to use bots to interact with the site, therefore, they have a very good system to detect this type of behavior. Executing the same request over and over from the same IP is definitely this type of behavior so you got a temporary ban from them. I didn't search for how long the ban least, but I suppose it will be around 24 hours. Also, the ban is for a specific endpoint, so you should be still able to log in and do other tasks.

**Comment by marievixezonaki** [comment]
Thanks a lot! Yes, it seems that this is the issue.
