### ISSUE TITLE
only follow action can not work, response always feedback_required

### ISSUE THREAD

**Issue by lzssd** [instagram4j/instagram4j#538]
other interface works fine, but follow action(/api/v1/friendships/create) always return feedback_required.
{
	"message": "feedback_required",
	"spam": true,
	"feedback_title": "Try Again Later",
	"feedback_message": "We restrict certain activity to protect our community. Tell us if you think we made a mistake.",
	"feedback_url": "repute/report_problem/instagram_follow_users/?violation_type\u0026responsible_policy=Ig.Policy.Engagement.TallyCluster.IPSpacesSessionNoVerifiedCountryFollow",
	"feedback_appeal_label": "Tell us",
	"feedback_ignore_label": "OK",
	"feedback_action": "report_problem",
	"category": "instagram_follow_users",
	"status": "fail"
}

Is there something wrong with this interface?

**Comment by khale11** [comment]
He doesn't know.

**Comment by jvogit** [comment]
Instagram has temporarily blocked you. Please refrain from executing too many actions in a short amount of time. Also know that the age of the account and its trust factor are also taken into account, in addition to, what actions you may perform.

In general, please try to keep it human like otherwise Instagram will detect this as botting.
