### ISSUE TITLE
How do I get follower / following in version 2.0.0?

### ISSUE THREAD

**Issue by chitoadinugraha** [instagram4j/instagram4j#539]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

How do I get follower / following in version 2.0.0?

**Comment by jvogit** [comment]
See [here](https://github.com/instagram4j/instagram4j/blob/08db2b5d5f8caaf731506ee2d8200e34e5651ddc/src/examples/java/friendships/FriendshipsTest.java#L70)

FriendshipsFeedsRequest with a FriendshipsFeeds.FOLLOWER or FOLLOWING

We also have a Discord you may join to ask more question instead of using GitHub issues
[![Discord](https://img.shields.io/discord/777326687326044171?label=chat)](https://discord.com/invite/gR2EPwZGEZ)
