### ISSUE TITLE
how to add line to story when user click see it or drag it up

### ISSUE THREAD

**Issue by lusicsmusics1** [instagram4j/instagram4j#580]
is ReelMetadataItem class property to add link to a story when we upload story by igClient.getActions().story().uploadPhoto

**Comment by jvogit** [comment]
If you're talking about the See More option like this 
![](https://i2.wp.com/blog.rebrandly.com/wp-content/uploads/2018/11/ig3.png?resize=411%2C733&ssl=1)

Only user with 10k+ followers can post a link in the story. I do not have the request for that either since I dont have account with so much followers! So I do not know the exact request for that. If you do happen to have the ability, please consider intercepting the request and sending the request details here or actually contribute to the project!

[Guide how to contribute and intercept requests](https://github.com/instagram4j/instagram4j/wiki/Contributing-Requests)
