### ISSUE TITLE
Followers feed only brings 99 results

### ISSUE THREAD

**Issue by RaitonGG** [instagram4j/instagram4j#642]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x ] I read the README.md
- [x ] I looked over the examples and wiki
- [x ] my issue hasn't been asked or solved before

---

### Describe the bug

Please provide a concise description of your bug and relevant code.

### How to reproduce

1. Specify steps to reproduce
```java
UserAction user = client.actions().users().findByUsername("username").join();
FeedIterable<FriendshipsFeedsRequest, FeedUsersResponse> followersFeed = user.followersFeed();
for(Profile profile : followersFeed.iterator().next().getUsers()){
//code
}
```
### Expected behavior

followersFeed.iterator().next().getUsers() should bring a list of every person following the user

### Actual behavior

followersFeed.iterator().next().getUsers() brings a list of the first 99 followers of user

**Comment by jvogit** [comment]
`followersFeed` returns an Iterable, because it is a paginated request. FeedIterable does this automatically when you loop through or use Iterator and call next. So every item in the iterable is one page of results (in your case one page of around 100 followers). This is why you only get 99 followers. You only requested one page by calling `followersFeed.iterator().next().getUsers()`

Here is short example using [Iterable in Java](https://www.programcreek.com/2012/10/loop-a-iterable-in-java/).

Additionally you can also use Java 8 stream with an Iterable by calling followersFeed.stream()

[Example from Wiki too](https://www.programcreek.com/2012/10/loop-a-iterable-in-java/)

So you can do something like
```java
for (FeedUsersResponse page : followersFeed){
    // process page
}
```

**Comment by RaitonGG** [comment]
Dumb me.... so it actually has multiple 99 users lists? 
Sorry for my poor java skills. 
Thank you so much for taking the time though! @jvogit

**Comment by ErrorxCode** [comment]
> Dumb me.... so it actually has multiple 99 users lists? Sorry for my poor java skills. Thank you so much for taking the time though! @jvogit

If your issue was resolved then **Close this issue**
